addpath '/mnt/nfs/share/Dropbox/Programs/current/zshehzad/mipavg4';

mipavgx('/mnt/nfs/share/eeg_test/CNV/0828121615_CNV_64chan.cnt', ...
        '/mnt/nfs/share/eeg_test/CNV/cnv.sgc', ...
        '/mnt/nfs/share/eeg_test/CNV/reject.arf', ...
        '-p /mnt/nfs/share/eeg_test/CNV/s01', ...
        '-o eegad', ...
        '-o eeglab', ...
        '-o econnectome');

mipavgx('/mnt/nfs/share/eeg_test/Faces_Greebles/0828121615_Face_Greebles_64chan.cnt', ...
        '/mnt/nfs/share/eeg_test/Faces_Greebles/N170.sgc', ...
        '/mnt/nfs/share/eeg_test/Faces_Greebles/reject.arf', ...
        '-p /mnt/nfs/share/eeg_test/Faces_Greebles/s01', ...
        '-o eegad', ...
        '-o eeglab', ...
        '-o econnectome');

mipavgx('/mnt/nfs/share/eeg_test/P300_Names/0828121615_P300_Names_fix64chan.cnt', ...
        '/mnt/nfs/share/eeg_test/P300_Names/0828121615_P300_Names_var64chan.cnt', ...
        '/mnt/nfs/share/eeg_test/P300_Names/P300_fix.sgc', ...
        '/mnt/nfs/share/eeg_test/P300_Names/P300_var.sgc', ...
        '/mnt/nfs/share/eeg_test/P300_Names/reject.arf', ...
        '-r M1,M2'
        '-p /mnt/nfs/share/eeg_test/P300_Names/s01', ...
        '-o eegad', ...
        '-o eeglab', ...
        '-o econnectome');

mipavgx('/mnt/nfs/share/eeg_test/VEP/0828121615_VEP.cnt', ...
        '/mnt/nfs/share/eeg_test/VEP/vep.sgc', ...
        '/mnt/nfs/share/eeg_test/VEP/reject.arf', ...
        '-p /mnt/nfs/share/eeg_test/VEP/s01', ...
        '-r all; HEOG, VEOG, EKG, EMG', ...
        '-o eegad', ...
        '-o eeglab', ...
        '-o econnectome');



mipavg4('/Users/zarrar/Projects/mipavg/0411121600_abscreen01_run01.cnt', ...
            '/Users/zarrar/Projects/mipavg/0411121600_abscreen01_run02.cnt', ...
            '/Users/zarrar/Dropbox/Programs/current/zshehzad/mipavg4/tests/sample.sgc', ...
            '/Users/zarrar/Dropbox/Programs/current/zshehzad/mipavg4/tests/sample.arf', ...
            '-b /Users/Shared/eeglab; /Users/Shared/fieldtrip', ...
            '-r all; HEOG, VEOG, EKG, EMG', ...
            '-p /Users/zarrar/Projects/mipavg/output', ...
            '-o eegad', ...
            '-o eeglab', ...
            '-o econnectome')

varargin = {'/Users/zarrar/Projects/mipavg/0411121600_abscreen01_run01.cnt', ...
            '/Users/zarrar/Projects/mipavg/0411121600_abscreen01_run02.cnt', ...
            '/Users/zarrar/Dropbox/Programs/current/zshehzad/mipavgx/tests/sample.sgc', ...
            '/Users/zarrar/Dropbox/Programs/current/zshehzad/mipavgx/tests/sample.arf', ...
            '-p /Users/zarrar/Projects/mipavg/output', ...
            '-o eegad', ...
            '-o eeglab', ...
            '-o fieldtrip'}

mipavgx(varargin{:})

cfg = [];
cfg.continuous = 'true';
cfg.dataset = '/Users/zarrar/Projects/tmp.set';
cfg.trialdef.eventtype = 'trigger';
cfg.trialdef.eventvalue = num2strcell(1);
cfg.trialdef.prestim = -1 * epoch(1)/1000;
cfg.trialdef.poststim = epoch(2)/1000;
cfg = ft_definetrial(cfg)

cfg_test = [];
cfg_test.continuous = 'true';
cfg_test.dataset = EEGfiles{1};
cfg_test.dataformat           = 'ns_cnt32';
cfg_test.headerformat         = 'ns_cnt32';
cfg_test.eventformat          = 'ns_cnt32';
cfg_test.trialdef.eventtype = 'trigger';
cfg_test.trialdef.eventvalue = [1:7, 101:166];
cfg_test.trialdef.prestim = epoch(1)/1000;
cfg_test.trialdef.poststim = epoch(2)/1000;
cfg_test = ft_definetrial(cfg_test)
